name: master_thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tqdm
  - nvidia-ml-py
  - psutil
  - py-cpuinfo
  - numpy
  - pip
  - pip: # Use CUDA 11.8 for better compatibility on INESC Machines
      - torch==2.5.1+cu118
      - torchvision==0.20.1+cu118
      - torchaudio==2.5.1+cu118
      - --extra-index-url https://download.pytorch.org/whl/cu118
