name: master_thesis_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tqdm
  - nvidia-ml-py
  - psutil
  - py-cpuinfo
  - numpy
  - scikit-learn
  - python-dotenv
  - matplotlib
  - requests
  - pip
  - pip: 
      - torch==2.9.1+cu129
      - torchvision==0.24.1+cu129
      - torchaudio==2.9.1+cu129
      - --extra-index-url https://download.pytorch.org/whl/cu129
