name: master_thesis_env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - tqdm
  - nvidia-ml-py
  - psutil
  - py-cpuinfo
  - numpy
  - pytorch
  - torchvision
  - torchaudio
  - cudatoolkit  
